### PR TITLE
Layout

### PR DESCRIPTION
**Pull request by jcromerohdz**
this branch include the embedding images and video project

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Hi there team
Nice job doing your first project. But before I give :+1: on it, we need to make some changes in order to make it in order with Microverse guidelines.

- [x] Your nav must be horizontal just like the youtube page.

- [x] The search bar must be aligned to the middle of the navbar

- [x] Must have at least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar

- [x] Try to mimic the layout of the youtube page. Doesn't need to look the same. A similar layout it's good enough.

- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

Please kindly make these changes and submit for code review again.

**Comment by jcromerohdz** [comment]
we fix the issues you commented above @Torres-ssf  could you please review the project again?

**Comment by samgaco** [comment]
### Hi @jcromerohdz and @lhscar56  :vulcan_salute: 

### You implemented some of the changes very well :+1:  but still:

* You have to correct the errors given to you by the [validator](https://validator.w3.org). (Upload the index.html file to see them, and try to correct them one by one)
* [OPTIONAL] You still could try to make the layout more similar to the one of the original website (youtube)

### Please :pray:  work on this, and submit back for another code review when you are done. You are doing well, keep the good work :muscle:

**Review by mosaaleb — APPROVED** [review]
##### Congratulations @jcromerohdz @lhscar56 :clap:

You can merge into master :+1: 

Good luck with the next projects.

**Pull request merged**
